DROP INDEX IF EXISTS lead_requests_deadline_idx;
DROP INDEX IF EXISTS lead_requests_protocol_idx;
ALTER TABLE lead_requests DROP CONSTRAINT lead_requests_status_check;
ALTER TABLE lead_requests ADD CONSTRAINT lead_requests_status_check CHECK (status IN ('new','reviewing','closed'));
ALTER TABLE lead_requests DROP COLUMN IF EXISTS updated_at;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS deadline_at;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS internal_notes;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS assigned_to;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS contact_consent;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS payment_preference;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS date_flexibility;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS baggage;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS cabin_class;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS infants;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS children;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS adults;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS customer_phone;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS customer_email;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS customer_name;
ALTER TABLE lead_requests DROP COLUMN IF EXISTS protocol;
DELETE FROM schema_migrations WHERE version='0004_flight_quote_center';
